### PR TITLE
Use parameter instead of hardcoded "manual"

### PR DESCRIPTION
**Pull request by grgrzybek**
@davsclaus @janstey wdyt?

### CODE REVIEW

**Comment by davsclaus** [comment]
lgtm

@janstey  this needs to be updated in the chapter where the source code for this class is shown

**Comment by grgrzybek** [comment]
sure - I added such info to my questionaire

**Comment by davsclaus** [comment]
@janstey I think this PR should be merged and the content in the chapter updated accordingly.

**Comment by janstey** [comment]
Thx @grgrzybek ! I've updated the chapter too.

**Pull request merged**
